:application:
    :name: "witty name"
:database:
  :development: 'development.db'
  :test: 'test.db'
  :production: 'production.db'
:services:
    :flickr:
        :api_key: ''
        :nsid: ''
    :twitter:
        :username: ''